language: node_js
node_js:
- '0.10'
deploy:
  - provider: heroku
    strategy: git
    api_key:
      secure: n7MQejUxkS1zdZ5BoMOSfM5VoJewawuJJYOc6FHY2oqnwzdEXc6ATcTYO9TJl7hEa9tB6lAhi92ju8u0Qs1hdvrlpQxLyJ/j3kgW8LqEW8Fr8lhI24zAQgvvdbqCTBpS05GcXRHLVmQ1bnTTqARD0d7TjGxqlhh9GXN1j03F96A=
    app:
      master: kanmu-hubot
    on:
      repo: kanmu/kanmukun
  - provider: heroku
    strategy: git
    api_key:
      secure: n7MQejUxkS1zdZ5BoMOSfM5VoJewawuJJYOc6FHY2oqnwzdEXc6ATcTYO9TJl7hEa9tB6lAhi92ju8u0Qs1hdvrlpQxLyJ/j3kgW8LqEW8Fr8lhI24zAQgvvdbqCTBpS05GcXRHLVmQ1bnTTqARD0d7TjGxqlhh9GXN1j03F96A=
    app:
      master: kanmu-hubot-nightshift
    on:
      repo: kanmu/kanmukun
